<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d4f828d2e8ab75d05c7281e
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
//dependency import
require 'properties.php';
require 'lib/Slim/Slim.php';
require 'security/Security.php';

//init Slim Framework
\Slim\Slim::registerAutoloader();
$app = new \Slim\Slim();
$app->add(new \Security($app));
require 'security/Login.php';
require 'security/ManageUser.php';

//resources
	//db fundacion_db
		require('./resource/fundacion_db/custom/AreasCustom.php');
		require('./resource/fundacion_db/Areas.php');
		require('./resource/fundacion_db/custom/ContactoCustom.php');
		require('./resource/fundacion_db/Contacto.php');
		require('./resource/fundacion_db/custom/EmpresaCustom.php');
		require('./resource/fundacion_db/Empresa.php');
		require('./resource/fundacion_db/custom/ObjetivosCustom.php');
		require('./resource/fundacion_db/Objetivos.php');
		require('./resource/fundacion_db/custom/QuienesCustom.php');
		require('./resource/fundacion_db/Quienes.php');
		require('./resource/fundacion_db/custom/SliderCustom.php');
		require('./resource/fundacion_db/Slider.php');
		require('./resource/fundacion_db/custom/UserCustom.php');
		require('./resource/fundacion_db/User.php');
	

$app->run();


?>
